// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiIieW65jWEV97qHXJuTF4XMkmsvyFJEg',
    appId: '1:157457266727:web:fc478a2a9a60ca8143b602',
    messagingSenderId: '157457266727',
    projectId: 'smartbike-5e0fe',
    authDomain: 'smartbike-5e0fe.firebaseapp.com',
    databaseURL: 'https://smartbike-5e0fe-default-rtdb.firebaseio.com',
    storageBucket: 'smartbike-5e0fe.firebasestorage.app',
    measurementId: 'G-9709G6ERLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVZ1DYH3YxI-iZidOw1izlRcQYZSBjIzM',
    appId: '1:157457266727:android:ac79b8bce59e9cd043b602',
    messagingSenderId: '157457266727',
    projectId: 'smartbike-5e0fe',
    databaseURL: 'https://smartbike-5e0fe-default-rtdb.firebaseio.com',
    storageBucket: 'smartbike-5e0fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm4Znz1Rj4i7vVN3UiYjMhCR52OFfwZmk',
    appId: '1:157457266727:ios:17151fb6ecce6bf743b602',
    messagingSenderId: '157457266727',
    projectId: 'smartbike-5e0fe',
    storageBucket: 'smartbike-5e0fe.firebasestorage.app',
    iosBundleId: 'com.example.smartbike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiIieW65jWEV97qHXJuTF4XMkmsvyFJEg',
    appId: '1:157457266727:web:561ecdd1fbff38fa43b602',
    messagingSenderId: '157457266727',
    projectId: 'smartbike-5e0fe',
    authDomain: 'smartbike-5e0fe.firebaseapp.com',
    databaseURL: 'https://smartbike-5e0fe-default-rtdb.firebaseio.com',
    storageBucket: 'smartbike-5e0fe.firebasestorage.app',
    measurementId: 'G-CER5MB022P',
  );
}
